
# User defined parameters, these can and should be change to specify input
# inputs to the workflow
# =============================================================================
variable_region_definitions:
  initiation_regions: 'config_files/variable_regions/initiation_plamids_rlooper.tsv'



# =============================================================================
# Program constants and parameters you can but probably don't need to
# change

# Path to default primer3 template file. This file is formatted from a python
# script so it is not recommended to change the actual path but if you want
# to change primer3 parameters that can be easily done by adjusting the
# default file's contents. Just watch out for "{}" those get filled by python
# with sequence specific info.
PRIMER3_TEMPLATE: 'resources/files/primer3_settings_template.txt'

# number of different sequence to generate for each variable region definition
# increasing this value will increase run time but generally increase
# quality of final sequence
EXPECTATION_SAMPLES: 50

# Number of random sequences used to calculate sequence metric expectations.
# Increasing this value will increase run time but produce a more accurate
# expectation for each metric
EXPECT_SAMPLES: 200

# =============================================================================
# Important parameter definitions that will definitely impact the workflow if
# changed. Avoid changing without good reason. 

RLOOPER_FILE_SUFFI:
  - 'avgG.wig'
  - 'bpprob.wig'
  - 'bpprob.bed'
  - 'mfe.bed'
  - 'mfe.wig'

SPOT_RNA_EXTS:
  - 'bpseq'
  - 'ct'
  - 'prob'


EXPECTATION_DEFS:
  # defines what a "good" value for each sequence metric looks like.
  # direction and divergence should either be 1 or -1.
  # direction: defines if metric value should be to the right (1) or left (-1)
  # of the metric expectation. Is only really important if divergence = 1.
  # divergence: defines if the distance (in standard deviations) from the
  # metric expectation should minimized (-1) or maximized (1).
  bp_prob:
    direction: 1  
    divergence: 1
  local_average_energy:
    direction: -1
    divergence: 1
  prop_hairpin:
    direction: -1
    divergence: 1
  prop_unpaired:
    direction: 1
    divergence: 1




