# User defined parameters, these can and should be change to specify input
# inputs to the workflow
# =============================================================================

# Variable regions parameters filepaths. Defines the sequence content
# of all variable regions that should be generated.
variable_region_definitions:
  insert_sequences_100_v2: 'config_files/variable_regions/variable_regions.tsv'

# List of names of restriction enzymes who's recognition sites should not be
# present in any generated sequence. Case sensitive. 
prohibited_restriction_enzyme_recognition_sites:
  - 'EcoRI'
  - 'KpnI'
  - 'SacI'
  - 'HindIII'

# List of paths to genbank formatted files describing plasmid backbones that inserts
# will be cloned into
backbones:
  t7_termination: 'resources/files/genbank/pFC8.gb'
  t7_initiation: 'resources/files/genbank/pFC9.gb'
  tac: 'resources/files/genbank/pFC53tacT1T2.gb'

# "Strong initiator" sequence that will be used as the initiator in the
# T7 termination series constructs. 
termination_series_initiator: 'resources/files/genbank/placeholder_initiator.gb'


insert_design:
  upstream_regions:
    - "resources/files/genbank/5_prime_homology_arm.gb"
  downstream_regions:
    - "resources/files/genbank/3_prime_homology_arm.gb"
  homology_target_backbone:
    'resources/files/genbank/pFC9.gb'
  feature_annotations:  # additional annotations to be added to variable region
    author: 'Ethan Holleman'
  design_version: "1.0"

rclone:
  exe: 'rclone'
  remote: 'davis-gdrive:backups/lab_data/VR_plasmid_design'
  sync: True


# =============================================================================
# Program constants and parameters you can but probably don't need to
# change

# Path to default primer3 template file. This file is formatted from a python
# script so it is not recommended to change the actual path but if you want
# to change primer3 parameters that can be easily done by adjusting the
# default file's contents. Just watch out for "{}" those get filled by python
# with sequence specific info.
PRIMER3_TEMPLATE: 'resources/files/primer3/primer3_settings_template.txt'

# number of different sequence to generate for each variable region definition
# increasing this value will increase run time but generally increase
# quality of final sequence
NUMBER_REPLICATES: 100

# Number of random sequences used to calculate sequence metric expectations.
# Increasing this value will increase run time but produce a more accurate
# expectation for each metric
# DEPRECIATED. This was used to when purely random sequences were used to
# inform sequence ranking. Kept in pipeline in case want to generate random
# sequences in the future. 
EXPECT_SAMPLES: 200

# Parameters defining how the anchor sequence is calculated
anchor_sequence:
  max_attempts: 100  # number of attempts to create anchor, avoids endless loop
  min_melting_temp: 48  # min melting temperature of anchor
  anchor_length: 15  # length of the anchor

  
# =============================================================================
# Important parameter definitions that will definitely impact the workflow if
# changed. Avoid changing without good reason. 

# file suffi produced by R-looper in one run.
RLOOPER_FILE_SUFFI:
  - 'avgG.wig'
  - 'bpprob.wig'
  - 'bpprob.bed'
  - 'mfe.bed'
  - 'mfe.wig'

# file suffi produced by spot-rna for one run 
SPOT_RNA_EXTS:
  - 'bpseq'
  - 'ct'
  - 'prob'

# defines what a "good" value for each sequence metric looks like.
EXPECTATION_DEFS:
  bp_prob: 'max' 
  local_average_energy: 'min'
  prop_hairpin: 'min'
  prop_unpaired: 'max'




